### ISSUE TITLE
Civetta Scintilla - You are now a cop

### ISSUE THREAD

**Issue by SunnySkye** [Raceless-RLS/rls_career_overhaul#21]
I added blue flashers to my Civetta Scintilla, and as expected I became a cop.
Police still chased me though, even with my flashers on, and even while I was chasing criminals.
Also, when I escape the police, I get "the suspect escaped, here's -$750 for repairs", and it takes $750 from me.

I removed the blue flashers but that has not changed anything, so now I lose $750 any time the cops chase me and I escape.

Not sure if this affects other cars, or if there is some way to reverse what has happened to my Scintilla.

**Comment by SunnySkye** [comment]
![image](https://github.com/user-attachments/assets/c6796e3c-9e71-40be-a103-c357af4b1729)

**Comment by TristanGaldys** [comment]
Thanks for bringing this up. First just wanted to let you know that you are 100% getting $750 every time you just are not monitoring how much cash you have. This is just a UI Bug it will be removed in the next update also the flasher thing is because the flashers are still apart of the inventory, If you sell the flashers in the parts inventory I would assume this would be fixed Ill see if i can make the system only check if the part is currently on the vehicle rather than in the inventory.

**Comment by TristanGaldys** [comment]
This was fixed as of 2.1
